# Here you can specify default options for TinyMCE across all controllers
#
# theme: advanced
# plugins:
#  - table
#  - fullscreen
plugins:
  - flags
theme: advanced
theme_advanced_toolbar_location: top
theme_advanced_buttons1: "bold,italic,underline,separator,justifyleft,justifycenter,justifyright,indent,outdent,separator,bullist,numlist,separator,link,unlink,image,separator,undo,redo,code,separator,pasteword,flags"
theme_advanced_buttons2: ""
theme_advanced_buttons3: ""
